{% set name = "molsystem" %}
{% set version = "2022.7.24" %}
{% set sha256 = "74be5122e25202ff2a778b4ba8b212b353c095e9eac023bcf691e2aca5f072a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/ea/30/0ccbca9d082be2a758d2af8d89bd547af849a0b15b0c42ac0b9cbb1cd971/molsystem-2022.7.24.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - pycifrw
    - python >=3.8
    - rdkit
    - seekpath
    - spglib

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
