{% set name = "molsystem" %}
{% set version = "2023.11.19" %}
{% set sha256 = "ba06232782ab135c33ec4e321eb95aab10164b0a3de6ac41a7b7f31c833a5ddc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/molsystem/molsystem-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - ply
    - pubchempy
    - pycifrw
    - python >=3.8
    - rdkit
    - seamm-util
    - seekpath
    - spglib

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
