{% set name = "molsystem" %}
{% set version = "2026.9.25" %}
{% set sha256 = "024a6886af2b800df7e40c1f54bc8dd091ddb10827643dc6b7e70939971b9fdc" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/m/molsystem/molsystem-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - mendeleev
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - ply
    - pycifrw
    - python >={{ python_min }}
    - rdkit
    - scipy
    - seamm-util
    - seekpath
    - spglib

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
