{% set name = "molsystem" %}
{% set version = "2022.8.5" %}
{% set sha256 = "8fc3d398bd188b74d94d838fd0a2b5fed5f7b90b2d9ed88c16af823212348da2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b3/8f/0780af39d40600cc26c5451e795216b08099d7efca0bc569ed0b1f4c952c/molsystem-2022.8.5.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - pycifrw
    - python >=3.8
    - rdkit
    - seekpath
    - spglib

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
