{% set name = "molsystem" %}
{% set version = "2025.3.4" %}
{% set sha256 = "2451899ad47c970e368020153cd3b9f118f54681f6ce63f5bf91b5701527485f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/molsystem/molsystem-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - ply
    - pycifrw
    - python >=3.8
    - rdkit
    - seamm-util
    - seekpath
    - spglib

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
