{% set name = "molsystem" %}
{% set version = "2026.1.28" %}
{% set sha256 = "47249a815d54b0f15f25f852cf3c6fd45f818e58e0dba507b5cf6ac332a9483e" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/molsystem/molsystem-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - ply
    - pycifrw
    - python >={{ python_min }}
    - rdkit
    - seamm-util
    - seekpath
    - spglib

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
