{% set name = "molsystem" %}
{% set version = "2022.1.15" %}
{% set sha256 = "6b0c73194e1c228a57879893d84e60bb7e4e20251196e36ef91d6bf1b3a7e78e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - pycifrw
    - python >=3.8
    - rdkit

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
